version: '3.9'

services:
  node:
    build: .
    volumes:
      - .:/data
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
  alpine:
    build: ./alpine
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      - node